// Hand-written, course-specific learning outcomes keyed by slug.
// Each entry is an 8-item list of applied competencies a student will
// demonstrate on completion. Mention real tools, platforms, and techniques
// so the list reads as though it were authored for this program.

export const LEARNING_OUTCOMES: Record<string, string[]> = {
  // ─── Web3 & Crypto ──────────────────────────────────────────────────────
  "nft-flipping-masterclass": [
    "Identify undervalued digital assets before broader market recognition",
    "Apply rarity-scoring methodology and floor-sweep analysis",
    "Use professional-grade market tools (NFTNerds, Icy.tools, Blur) effectively",
    "Time position exits for maximized return",
    "Construct a repeatable trading system with measurable performance",
    "Implement tax-efficient strategies for digital asset trading",
    "Recognize and avoid high-frequency beginner errors",
    "Analyze real case studies of 10x+ position outcomes",
  ],
  "bitcoin-ordinals": [
    "Explain Bitcoin Ordinals architecture and the inscription process end-to-end",
    "Mint inscriptions on Unisat, Gamma, and OrdinalsBot with correct fees",
    "Evaluate early Ordinals projects using on-chain and market data",
    "Navigate BRC-20 token mechanics and secondary marketplaces",
    "Use Magic Eden Ordinals and Ordinals Market proficiently",
    "Identify project-level risk indicators and protect capital",
    "Configure secure Bitcoin wallet infrastructure for Ordinals",
    "Construct a research-driven Ordinals portfolio methodology",
  ],
  "solana-defi-mastery": [
    "Navigate Solana DeFi protocols — Jupiter, Raydium, Orca, Kamino, marginfi",
    "Execute swaps, limit orders, and DCA strategies on Jupiter Aggregator",
    "Provide liquidity on concentrated pools and manage impermanent loss",
    "Run leveraged strategies on marginfi and Kamino responsibly",
    "Use Birdeye, DexScreener, and Solscan for on-chain research",
    "Set up and secure a Phantom wallet with hardware-backed signing",
    "Size positions using risk-based position sizing for volatile assets",
    "Build a weekly Solana DeFi routine that compounds without overtrading",
  ],
  "crypto-day-trading": [
    "Read candlestick, volume profile, and order-book structure on BTC/ETH pairs",
    "Execute scalps and intraday swings using TradingView and Hyperliquid",
    "Apply fixed-risk position sizing with predefined stop placement",
    "Build trade plans around funding rates, open interest, and liquidation maps",
    "Manage perpetual leverage responsibly and avoid cascading liquidations",
    "Journal every trade and compute expectancy, win rate, and R-multiple",
    "Filter setups with a repeatable checklist to cut low-quality entries",
    "Recover from drawdown with rule-based reduction of size and frequency",
  ],
  "blockchain-development-solidity": [
    "Write, compile, and deploy Solidity contracts with Hardhat and Foundry",
    "Model ERC-20, ERC-721, and ERC-1155 token standards correctly",
    "Use OpenZeppelin contracts to ship secure, audited-pattern code",
    "Test contracts with unit, fuzz, and invariant tests (Foundry)",
    "Deploy to Ethereum, Arbitrum, Base, and Optimism with verified source",
    "Audit for reentrancy, integer overflow, and access-control bugs",
    "Integrate contracts with a front end using ethers.js / viem and wagmi",
    "Estimate gas accurately and apply gas-optimization patterns",
  ],
  "web3-freelancing": [
    "Package Web3-specific services (smart contracts, tokenomics, audits, dashboards)",
    "Win first clients on Earn.superteam, CryptoJobsList, and X / warpcast",
    "Price retainers and project work in stablecoins or native tokens",
    "Scope a smart-contract or dApp project with a defensible statement of work",
    "Invoice and receive payment in USDC with proper tax records",
    "Build a portfolio of on-chain work verifiable by contract address",
    "Negotiate equity, token grants, and milestone vesting in Web3 contracts",
    "Operate as a sole-trader Web3 consultant with sustainable deal flow",
  ],
  "crypto-fundamentals": [
    "Explain public-key cryptography, wallets, and seed-phrase security",
    "Distinguish Bitcoin, Ethereum, L2s, and major app-chains by design tradeoffs",
    "Buy, send, and hold crypto safely using exchanges and self-custody wallets",
    "Read a blockchain explorer (Etherscan, Solscan) to verify any transaction",
    "Evaluate a token using market cap, float, emissions, and holder distribution",
    "Avoid the common scams — approval drains, fake airdrops, Discord phishing",
    "Set up a hardware wallet and a safe signing workflow",
    "Build a long-term, low-stress crypto allocation you can actually hold",
  ],
  "defi-yield-farming": [
    "Evaluate yield sources — lending, LP, staking, points, restaking",
    "Compare APY vs. APR and decompose it into fees, emissions, and principal risk",
    "Deploy capital on Aave, Compound, Pendle, Curve, and Convex",
    "Manage impermanent loss on Uniswap v3 concentrated positions",
    "Use Pendle to separate principal and yield for fixed-rate strategies",
    "Assess smart-contract risk with audit reports, TVL history, and timelocks",
    "Diversify yield across chains (Ethereum, Arbitrum, Base) without over-bridging",
    "Track performance and rebalance with a simple spreadsheet or DeBank",
  ],
  "nft-collection-launch": [
    "Design a 1/1 or generative collection brief with clear brand identity",
    "Generate trait-based art in HashLips or custom pipeline and export metadata",
    "Write, test, and deploy an ERC-721A mint contract with allowlist support",
    "Run a presale, public mint, and reveal without gas-war incidents",
    "List on OpenSea, Blur, and Magic Eden with royalties configured correctly",
    "Build community on Discord and X before mint to avoid empty-launch risk",
    "Handle post-mint operations — holder benefits, floor management, roadmap",
    "Measure launch success with secondary volume, holder count, and sweep rate",
  ],
  "smart-contract-auditing": [
    "Apply a structured audit methodology — scoping, threat modeling, review, report",
    "Identify reentrancy, oracle manipulation, and price-feed abuse patterns",
    "Detect access-control and upgradeability bugs in proxy contracts",
    "Use Slither, Mythril, and Echidna for static and fuzz analysis",
    "Write Foundry invariant tests that expose economic exploits",
    "Review real audit reports (Trail of Bits, Spearbit, Code4rena)",
    "Produce a professional audit deliverable with severity and remediation",
    "Participate productively in Code4rena and Sherlock contests",
  ],

  // ─── Marketing & Social ────────────────────────────────────────────────
  "twitter-x-growth-2026": [
    "Position an X profile so it converts visitors in under five seconds",
    "Write posts that earn reach under the 2026 algorithm's reply and depth signals",
    "Run a daily content cadence without burning out",
    "Build reply and DM funnels that turn followers into leads",
    "Use X Premium monetization and Creator revenue-share correctly",
    "Analyze reach, profile-clicks, and conversions with X Analytics",
    "Collaborate with accounts in your niche for compounding growth",
    "Ship a 90-day growth plan with concrete weekly targets",
  ],
  "instagram-growth-monetization-2026": [
    "Build a visual brand system — feed, Reels covers, Stories, highlights",
    "Shoot and edit Reels that ride the 2026 discovery algorithm",
    "Write hooks that survive the three-second retention cliff",
    "Open and sustain a DM-based sales motion from Reels traffic",
    "Run collaborative posts and Instagram Broadcast Channels for retention",
    "Set up UGC and brand-deal pricing with rate-card and usage rights",
    "Track saves, shares, and sends — the metrics Instagram actually rewards",
    "Monetize through affiliate, digital products, and brand deals in parallel",
  ],
  "tiktok-viral-content": [
    "Hook viewers in the first 1.3 seconds using proven opening patterns",
    "Structure 15-, 30-, and 60-second videos for full-watch completion",
    "Use trending audio and effects without diluting your niche",
    "Batch-film a week of content in a single session",
    "Edit tight cuts in CapCut with captions, B-roll, and pattern interrupts",
    "Read the TikTok Analytics trio — retention, for-you rate, and shares",
    "Recover from flop-streaks without resetting the algorithm signal",
    "Convert TikTok views into email subscribers and paying customers",
  ],
  "youtube-shorts-monetization": [
    "Script Shorts with a hook, promise, payoff, and loop in under 45 seconds",
    "Package titles and thumbnails that survive Shorts-to-long-form discovery",
    "Hit the YPP Shorts monetization thresholds deliberately, not accidentally",
    "Use the Shorts Fund, ad revenue share, and Super Thanks correctly",
    "Repurpose long-form content into Shorts without cannibalizing watch time",
    "Analyze RPM and CPM across niches to price sponsorships",
    "Set up and A/B test thumbnails with YouTube's built-in tool",
    "Build a Shorts-first channel and graduate into long-form and membership",
  ],
  "personal-branding-linkedin": [
    "Rewrite a LinkedIn profile to communicate a single, memorable positioning",
    "Post content types LinkedIn's 2026 algorithm rewards (carousels, long-form, polls)",
    "Build a weekly publishing rhythm without sounding corporate",
    "Leverage comments and DMs as your primary distribution surface",
    "Use LinkedIn Live and newsletter features to deepen audience",
    "Convert inbound DMs into sales calls with a simple qualification flow",
    "Track Social Selling Index and profile views to measure authority growth",
    "Attract inbound job offers, clients, or speaking invitations predictably",
  ],
  "facebook-ads-mastery": [
    "Design a full-funnel Meta Ads account structure — prospecting, retargeting, retention",
    "Launch campaigns in Meta Ads Manager with correct objective and placement choices",
    "Write ad copy frameworks — PAS, 4Us, and AIDA — for cold traffic",
    "Test creatives systematically using the iOS-14-era CBO + dynamic creative stack",
    "Interpret ROAS, CPA, and incremental lift without being fooled by platform-reported numbers",
    "Set up the Conversions API and Pixel correctly for iOS 14.5+ tracking",
    "Scale winners vertically and horizontally without breaking account economics",
    "Diagnose and fix fatigue, frequency, and policy issues before they kill performance",
  ],
  "google-ads-beginners": [
    "Choose the right campaign type — Search, Performance Max, YouTube, Display",
    "Structure a Google Ads account by theme, intent, and match-type discipline",
    "Research keywords and build negative-keyword lists that protect budget",
    "Write responsive search ads and extensions that improve quality score",
    "Bid with target CPA, target ROAS, and manual CPC appropriately",
    "Build landing pages that convert paid traffic at 2×+ baseline rates",
    "Read Search Term and Auction Insights reports to find wasted spend",
    "Launch, manage, and optimize a small-business account profitably",
  ],
  "seo-fundamentals-2026": [
    "Explain how search — Google, Bing, and AI-answer engines — now ranks content",
    "Do keyword research that balances volume, intent, and AI-answer coverage",
    "Produce on-page SEO that wins in both classic SERPs and AI Overviews",
    "Fix the technical SEO issues (indexation, Core Web Vitals, canonicals) that throttle growth",
    "Build topical authority with a cluster-and-pillar content plan",
    "Earn backlinks with digital PR and linkable-asset tactics",
    "Use GSC, Ahrefs, and Screaming Frog to diagnose any site in under an hour",
    "Set up reporting that shows SEO's real contribution to revenue",
  ],
  "email-marketing-automation": [
    "Design welcome, nurture, abandoned-cart, and winback flows that actually convert",
    "Write email copy with a single clear call to action per send",
    "Segment a list by behavior, RFM, and engagement recency",
    "Build automations in Klaviyo (or ConvertKit / ActiveCampaign) from scratch",
    "Set up domain authentication — SPF, DKIM, DMARC — to protect deliverability",
    "Run A/B tests on subject lines, hero blocks, and send times with valid stats",
    "Measure revenue per recipient, not just open and click rates",
    "Recover a cold list without scorching the sending domain",
  ],
  "content-marketing-strategy": [
    "Anchor content to a positioning statement and a single ICP",
    "Build a pillar + cluster content map across formats (article, video, social)",
    "Run a weekly content production system that survives a busy quarter",
    "Brief writers and editors with standards that produce consistent quality",
    "Distribute each asset across owned, earned, and paid channels deliberately",
    "Measure content's contribution with assisted conversions, not vanity metrics",
    "Use analytics to retire losers and double down on winners",
    "Build a content engine that compounds pipeline month over month",
  ],
  "influencer-marketing": [
    "Identify the right tier of creator (nano, micro, mid, macro) for your budget",
    "Source creators on Instagram, TikTok, YouTube, and Modash / Grin",
    "Brief influencers for brand-safe creative that still performs on the FYP",
    "Negotiate usage rights, exclusivity, and whitelisting terms",
    "Structure deals — flat fee, affiliate, hybrid, equity — correctly",
    "Track UTM-coded links, promo codes, and view-through attribution",
    "Scale from single-campaign tests to an always-on creator program",
    "Avoid FTC disclosure and counterfeit-engagement pitfalls",
  ],
  "pinterest-marketing": [
    "Set up a Pinterest business account, rich pins, and claimed domains",
    "Design pins that win in the 2026 Pinterest visual-search ranking",
    "Plan seasonal content 45–90 days ahead of search peaks",
    "Schedule pins with Tailwind or native Pinterest tools",
    "Drive organic traffic to blog posts, Shopify stores, and lead magnets",
    "Run Pinterest Ads with keyword targeting at low CPCs",
    "Analyze top pins, saves, and outbound clicks to find repeatable winners",
    "Turn a Pinterest account into a steady, low-cost traffic source",
  ],
  "snapchat-marketing": [
    "Navigate Snap Ads Manager and choose the right objective per campaign",
    "Build Snap-native creative (vertical video, fast cuts, bold captions)",
    "Use Snap Pixel and Conversion API for accurate tracking",
    "Leverage Snap Spotlight and Public Profiles for organic reach",
    "Design AR Lenses via Lens Studio for brand campaigns",
    "Target Gen-Z and younger millennial audiences cost-effectively",
    "A/B test creatives on Snap's cheaper inventory before porting winners",
    "Measure incrementality vs. baseline, not just Snap-reported conversions",
  ],
  "podcast-marketing": [
    "Define a podcast concept with a single ICP and tight promise",
    "Record interviews and solo episodes with clean, broadcast-grade audio",
    "Edit in Descript or Riverside without overproducing",
    "Write show notes, chapters, and transcripts that win search and AI answers",
    "Launch to the Apple / Spotify charts with a deliberate week-one plan",
    "Grow with guest swaps, YouTube video podcasting, and short-form clips",
    "Monetize with sponsors, premium feeds, and digital products",
    "Measure downloads-per-episode and listener retention honestly",
  ],
  "affiliate-marketing-empire": [
    "Pick an affiliate niche with recurring commissions and product-market fit",
    "Choose networks — ShareASale, Impact, PartnerStack, Amazon, CJ — by fit",
    "Build a content site that earns qualified search traffic month over month",
    "Write review and comparison articles that win affiliate-intent keywords",
    "Drive email-list growth that compounds affiliate revenue per subscriber",
    "Negotiate private rates and bonuses with affiliate managers",
    "Comply with FTC and GDPR disclosure requirements",
    "Scale a portfolio of affiliate sites or channels without burning out",
  ],

  // ─── E-Commerce ────────────────────────────────────────────────────────
  "dropshipping-mastery-2026": [
    "Research winning products using TikTok, Minea, and PPSpy",
    "Set up a conversion-ready Shopify store with a fast, trust-heavy theme",
    "Source suppliers on AliExpress, CJ Dropshipping, and Zendrop with QC",
    "Write product pages with hero shots, trust stacks, and risk reversal",
    "Launch profitable Facebook and TikTok ad campaigns with UGC creative",
    "Install Shopify apps (Vitals, Judge.me, ReConvert) without slowing the store",
    "Handle refunds, chargebacks, and customer-service escalations",
    "Transition a winning product from dropshipping to private-label economics",
  ],
  "amazon-fba-private-label": [
    "Research product opportunities with Helium 10, Jungle Scout, and Cerebro",
    "Source from Alibaba and 1688 with QC checkpoints and golden samples",
    "Design packaging and insert cards that create repeat buyers",
    "Launch with Vine, PPC, and deliberate review velocity (TOS-safe)",
    "Write listings — title, bullets, A+ — for both Amazon search and the buy-box",
    "Run PPC with manual, auto, broad/phrase/exact, and Sponsored Brands",
    "Manage inventory with forecasting, reorder points, and storage-fee control",
    "Scale to multi-SKU brand economics without drowning in working capital",
  ],
  "etsy-shop-empire": [
    "Pick an Etsy niche with genuine buyer demand, not just search volume",
    "Photograph products with natural light and lifestyle scenes that convert",
    "Write Etsy SEO titles, tags, and descriptions that rank in 2026",
    "Price products with COGS, fees, and Etsy Ads baked into margin",
    "Run Etsy Offsite Ads and Etsy Ads profitably (not just for traffic)",
    "Deliver a customer experience that earns five-star reviews by default",
    "Diversify beyond Etsy to a Shopify flagship when ready",
    "Scale from side-hustle shop to multi-SKU brand without burning out",
  ],
  "print-on-demand-blueprint": [
    "Pick niches with passionate buyers and evergreen gift intent",
    "Design in Canva, Photoshop, and Midjourney for POD print quality",
    "Use Printify, Printful, and Gelato for product and margin optimization",
    "Sell on Etsy, Shopify, Amazon Merch, and Redbubble without channel conflict",
    "Test 20 designs fast and let data pick the winners",
    "Write listings that rank on Etsy and Amazon search in 2026",
    "Run low-budget Pinterest and TikTok traffic to breakout designs",
    "Build a library of evergreen sellers that compounds year over year",
  ],
  "amazon-kdp-publishing": [
    "Pick low-content and medium-content book niches that still have opportunity",
    "Use Publisher Rocket and KDSpy to validate demand before you design",
    "Design interiors and covers that meet KDP print specs on the first upload",
    "Price books and assign categories and keywords for maximum reach",
    "Run Amazon Ads for books — auto, manual, product, category — profitably",
    "Stack low-content notebooks, journals, and puzzle books into a backlist",
    "Launch a fiction or nonfiction title with a clean week-one playbook",
    "Track royalties across KDP, audiobook, and international markets",
  ],
  "ebay-reselling": [
    "Source inventory at thrift stores, estate sales, liquidation, and clearance",
    "Spot high-sell-through items using eBay's sold-listings and Terapeak",
    "Photograph, measure, and list items with pro-grade descriptions",
    "Price with Buy-It-Now, best offer, and auction — each for the right use case",
    "Ship efficiently with eBay labels, flat-rate boxes, and SpeedPAK",
    "Handle returns, INADs, and feedback without damaging seller rating",
    "Track COGS, fees, and mileage to know real margin per item",
    "Scale to a consistent $3–10K/month reselling operation",
  ],
  "wholesale-distribution": [
    "Identify product categories with durable wholesale demand",
    "Source domestic and import suppliers and negotiate MOQ and Net-30 terms",
    "Set up warehouse, receiving, and cycle-count processes",
    "Price wholesale tiers with MSRP, MAP policy, and retailer margin protection",
    "Pitch and close independent retailers via Faire, trade shows, and cold outreach",
    "Handle logistics — LTL, FTL, and last-mile — cost-effectively",
    "Manage AR, AP, and working-capital cycles without cash crunches",
    "Graduate from selling to a few stores to a real regional distribution book",
  ],
  "digital-products-create-launch-sell": [
    "Pick a digital-product format (template, course, toolkit, ebook) that fits your audience",
    "Validate demand with pre-sales or a paid waitlist before you build",
    "Create the product in 2–4 weeks using a scoped-MVP approach",
    "Set up checkout on Gumroad, Lemon Squeezy, or Stripe + a simple landing page",
    "Launch to an audience with a 7-day email sequence that converts",
    "Write sales copy with proof, promise, and process — and a single CTA",
    "Run an evergreen funnel that sells while you sleep",
    "Price, bundle, and version to double revenue-per-visitor over time",
  ],
  "subscription-box-business": [
    "Pick a subscription-box niche with monthly unboxable theming",
    "Source products and negotiate COGS that supports subscription economics",
    "Design a box, insert cards, and unboxing that earns social shares",
    "Set up Cratejoy, Subbly, or Shopify with Recharge for recurring billing",
    "Launch with a waitlist, founding-member pricing, and a fulfillment partner",
    "Retain subscribers with a content calendar and anti-churn micro-surprises",
    "Handle logistics — pick, pack, ship — at 100, 500, and 1,000 subs",
    "Track LTV, churn, and contribution margin weekly, not monthly",
  ],
  "woocommerce-ecommerce": [
    "Install and configure WooCommerce on a WordPress host built for speed",
    "Pick a theme (Astra, Kadence, Blocksy) and customize without bloating the site",
    "Set up payments — Stripe, PayPal, Apple Pay — and taxes by region",
    "Configure shipping rates, zones, and real-time carrier APIs",
    "Install the essential plugins (WooCommerce, WPForms, Rank Math) and no more",
    "Optimize for Core Web Vitals so you rank and convert",
    "Integrate email (Klaviyo / Mailchimp), analytics, and abandoned-cart flows",
    "Hand off a maintainable WooCommerce build to a non-technical owner",
  ],
  "shopify-app-development": [
    "Scaffold a Shopify app with the App Bridge and Polaris using Remix or Next",
    "Use the Admin GraphQL API and Storefront API correctly",
    "Ship checkout extensions, theme app extensions, and web pixels",
    "Authenticate with OAuth and session tokens per 2026 Shopify requirements",
    "Build for the Partner Dashboard and pass App Store review on the first try",
    "Price with the Billing API and handle proration and trials",
    "Monitor with App Bridge analytics, logs, and error reporting",
    "Ship a first paying app and iterate based on merchant feedback",
  ],
  "ecommerce-email-funnels": [
    "Map a full revenue flow — welcome, browse, cart, post-purchase, winback",
    "Write welcome series that convert first-time browsers within 72 hours",
    "Build browse- and cart-abandonment flows with SMS back-stop in Klaviyo",
    "Design post-purchase sequences that lift AOV and LTV on repeat orders",
    "Segment with RFM and purchase behavior, not just engagement",
    "Run a weekly campaign calendar that compounds without unsubscribes",
    "Protect sender reputation with SPF, DKIM, and list hygiene",
    "Report on flow-attributed vs. campaign-attributed revenue accurately",
  ],

  // ─── Business ─────────────────────────────────────────────────────────
  "local-business-consulting": [
    "Pick a vertical (dentists, HVAC, med-spas) and build a repeatable offer",
    "Cold outreach and in-person prospecting that books qualified meetings",
    "Audit a local business's Google Business Profile, website, and ad accounts",
    "Run Google Local Services Ads, Google Ads, and Meta for local lead gen",
    "Build landing pages and missed-call-text-back systems that convert calls to jobs",
    "Price retainer + performance deals that lock in recurring revenue",
    "Onboard and retain clients with monthly reporting they actually read",
    "Scale the agency past solo practitioner with a first hire and SOPs",
  ],
  "business-plan-mastery": [
    "Articulate a business concept in a one-page summary that stands up to scrutiny",
    "Research the market, competitors, and TAM/SAM/SOM honestly",
    "Build a three-year P&L, cash-flow, and balance-sheet forecast",
    "Model pricing, unit economics, and break-even mathematically",
    "Write an operations, marketing, and hiring plan tied to the financials",
    "Identify the real risks and write mitigation strategies for each",
    "Package the plan for investors, lenders, and internal stakeholders",
    "Use the plan as a living tool — revisit quarterly and update rigorously",
  ],
  "virtual-assistant-business": [
    "Pick VA services that command premium rates (exec, tech, podcast, real-estate VA)",
    "Set up LLC, contracts, and invoicing to look like a real business day one",
    "Find first clients on LinkedIn, Upwork, OnlineJobs.ph, and cold email",
    "Onboard clients with a kick-off doc, access checklist, and SLAs",
    "Manage client work with ClickUp, Notion, or Asana without dropping balls",
    "Charge retainers instead of hourly to escape the time-for-money ceiling",
    "Subcontract overflow work to scale without burning out",
    "Build recurring revenue that replaces a full-time job in 6–12 months",
  ],

  // ─── Tech & Development ──────────────────────────────────────────────
  "freelance-web-dev-bootcamp": [
    "Build responsive marketing sites with HTML, CSS, and vanilla JavaScript",
    "Use Git, GitHub, and deploy to Vercel or Netlify with CI",
    "Design systems in Figma and translate designs to code",
    "Write accessible, performant HTML that scores 95+ on Lighthouse",
    "Offer freelance packages — landing pages, five-page sites, WordPress migrations",
    "Land first clients on Upwork, cold outreach, and local networking",
    "Price and scope projects with a fixed-fee contract and milestone deposits",
    "Deliver client work on time with a repeatable production process",
  ],
  "python-automation": [
    "Write idiomatic Python 3.12+ code with type hints, dataclasses, and f-strings",
    "Automate files, spreadsheets, and PDFs with openpyxl, pandas, and PyPDF",
    "Scrape the web responsibly with requests, BeautifulSoup, and Playwright",
    "Automate browsers for form-filling, QA, and data extraction",
    "Schedule scripts with cron, Task Scheduler, or GitHub Actions",
    "Send emails and messages via Gmail, Slack, and Discord APIs",
    "Package scripts into CLIs with Click or Typer",
    "Ship small automation tools that save hours per week at your day job",
  ],
  "react-nextjs-development": [
    "Build apps with the Next.js App Router, Server Components, and Server Actions",
    "Manage state with React Server Components, useState, and Zustand (when needed)",
    "Fetch data on the server with proper caching and revalidation",
    "Style with Tailwind CSS using a scalable design-token approach",
    "Implement auth with NextAuth / Auth.js and route protection",
    "Work with Prisma + PostgreSQL and run migrations safely",
    "Deploy to Vercel with environment management and preview URLs",
    "Ship a full-stack Next.js 16 app from scratch to production",
  ],
  "mobile-app-development": [
    "Build cross-platform apps with React Native and Expo in 2026",
    "Design with a navigation-first architecture (Expo Router or React Navigation)",
    "Call REST and GraphQL APIs with TanStack Query and proper caching",
    "Handle device features — camera, notifications, location, biometrics",
    "Persist data with AsyncStorage, MMKV, and SQLite",
    "Implement auth flows with Clerk, Supabase, or Firebase",
    "Publish to the App Store and Google Play, including review response",
    "Monitor crashes and analytics with Sentry and PostHog",
  ],
  "wordpress-development": [
    "Stand up a professional WordPress site with a lean theme and plugin stack",
    "Customize sites with block themes, patterns, and theme.json",
    "Build with Elementor or Bricks when client handoff matters",
    "Implement on-page SEO with Rank Math and structured data",
    "Harden security with Wordfence, 2FA, and proper user roles",
    "Speed up sites with caching, image optimization, and a CDN",
    "Back up, stage, and migrate sites safely between environments",
    "Ship freelance WordPress builds that don't come back with problems",
  ],
  "fullstack-javascript": [
    "Design full-stack apps with Node.js, Express or Hono, and a modern front end",
    "Model data with Prisma + PostgreSQL and write safe migrations",
    "Build REST and tRPC APIs with input validation (Zod) and error handling",
    "Implement auth — sessions, JWTs, OAuth — with sane defaults",
    "Test with Vitest, Playwright, and Supertest with meaningful coverage",
    "Deploy to Vercel, Railway, or Fly.io with env, secrets, and logs configured",
    "Observe production with structured logs, metrics, and error tracking",
    "Ship a portfolio-grade full-stack app end to end",
  ],
  "devops-cloud-engineering": [
    "Containerize applications with Docker and deploy to Kubernetes or ECS",
    "Write infrastructure as code with Terraform and reusable modules",
    "Build CI/CD pipelines with GitHub Actions, including preview envs",
    "Operate AWS core services (VPC, EC2, RDS, S3, CloudFront, IAM) competently",
    "Monitor with CloudWatch, Prometheus, and Grafana",
    "Apply security basics — least-privilege IAM, KMS, secrets management",
    "Run cost reviews monthly and cut waste with right-sizing and reservations",
    "Handle a production incident calmly with a post-mortem that actually ships fixes",
  ],
  "data-science-python": [
    "Load, clean, and transform data with pandas and DuckDB",
    "Visualize with matplotlib, seaborn, and Plotly for exploratory analysis",
    "Build regression, classification, and tree-based models with scikit-learn",
    "Tune hyperparameters with cross-validation and pipelines",
    "Explain models with SHAP and feature-importance methods",
    "Deploy models as APIs with FastAPI and containerize them",
    "Work inside Jupyter and VS Code notebook workflows productively",
    "Deliver a portfolio project end-to-end — data, model, deployment, write-up",
  ],
  "cybersecurity-fundamentals": [
    "Explain the CIA triad, threat modeling, and zero-trust principles",
    "Identify the OWASP Top 10 and how each vulnerability looks in real code",
    "Run vulnerability scans with Nmap, Nikto, and OpenVAS responsibly",
    "Practice web app testing with Burp Suite in a lab environment",
    "Harden Linux and Windows hosts with baseline security configurations",
    "Use SIEM basics — logs, alerts, and incident timelines",
    "Follow an incident-response playbook (NIST / SANS) in a tabletop exercise",
    "Prepare for Security+ and entry-level blue-team or SOC interviews",
  ],
  "sql-database-mastery": [
    "Write SELECT, JOIN, GROUP BY, and window-function queries fluently",
    "Design normalized schemas and denormalize intentionally for performance",
    "Build and maintain indexes — and know when not to",
    "Read an EXPLAIN plan in PostgreSQL / MySQL and fix slow queries",
    "Work with CTEs, subqueries, and recursive queries",
    "Handle transactions, isolation levels, and deadlocks in production code",
    "Model time-series and event data correctly",
    "Pass SQL interviews at analyst, engineer, and senior-engineer levels",
  ],
  "ios-app-development": [
    "Build iOS apps with SwiftUI and the latest iOS SDKs",
    "Structure apps with MVVM and Swift Concurrency (async/await)",
    "Persist data with SwiftData and CloudKit",
    "Call REST APIs with URLSession and decode JSON with Codable",
    "Integrate device features — camera, location, notifications, HealthKit",
    "Use In-App Purchase with StoreKit 2 for subscriptions",
    "Submit to the App Store with provisioning, screenshots, and review notes",
    "Publish a portfolio iOS app and iterate based on real user reviews",
  ],
  "android-app-development": [
    "Build Android apps with Kotlin, Jetpack Compose, and Material 3",
    "Structure apps with MVVM, Hilt DI, and the Android architecture components",
    "Persist data with Room and DataStore",
    "Call APIs with Retrofit, Moshi, and OkHttp correctly",
    "Integrate device features — camera, location, notifications, BLE",
    "Test with JUnit, Espresso, and Compose UI testing",
    "Publish to Google Play with signed bundles and a complete store listing",
    "Ship a polished Android app that passes Play Store review on the first try",
  ],

  // ─── Tech & AI ───────────────────────────────────────────────────────
  "ai-automation-business": [
    "Map business processes that are genuinely AI-replaceable vs. those that aren't",
    "Build automations in n8n, Make, and Zapier with AI nodes",
    "Use OpenAI, Anthropic, and open-source LLMs via API for real work",
    "Design prompts and system messages that produce reliable outputs",
    "Build a customer-support, sales, or content AI workflow end to end",
    "Handle errors, fallbacks, and human-in-the-loop checkpoints",
    "Measure ROI of each AI workflow with time-saved and error-rate metrics",
    "Sell AI-automation retainers to SMB clients with a repeatable discovery process",
  ],
  "prompt-engineering-mastery": [
    "Write prompts that get reliable, formatted output from ChatGPT and Claude",
    "Use system prompts, few-shot examples, and structured output (JSON schema)",
    "Chain prompts into multi-step workflows that handle real tasks",
    "Use function calling / tools for retrieval, search, and code execution",
    "Apply retrieval-augmented generation with a vector database (Pinecone / pgvector)",
    "Debug prompts systematically when models go off the rails",
    "Benchmark prompt versions against held-out examples",
    "Ship a production prompt-driven feature your team actually uses",
  ],
  "midjourney-ai-art": [
    "Write Midjourney v6+ prompts with subject, style, composition, and modifiers",
    "Control outputs with aspect ratios, styles references, and character references",
    "Use Vary, Zoom, Pan, and Remix to iterate toward a final image",
    "Build a consistent visual style across a full campaign or brand",
    "Upscale and export for print, web, and social",
    "Understand commercial-use rights and safe reference workflows",
    "Combine Midjourney with Photoshop and Magnific for final polish",
    "Sell AI-art services — book covers, ad creative, concept art — profitably",
  ],
  "ai-content-creation": [
    "Use ChatGPT, Claude, and Gemini as real writing collaborators, not magic buttons",
    "Generate first drafts fast and edit them to sound human and brand-safe",
    "Build content briefs the AI can execute with high accuracy",
    "Create video with Runway, Pika, and HeyGen without uncanny-valley output",
    "Produce images with Midjourney and DALL-E for articles and social posts",
    "Repurpose one piece of pillar content into 10+ assets across formats",
    "Keep AI content off the 'obvious-AI' spam list search and social punish",
    "Build an AI-augmented content workflow that ships weekly without burnout",
  ],
  "machine-learning-basics": [
    "Frame a real problem as supervised, unsupervised, or reinforcement learning",
    "Split, scale, and encode data the way production pipelines actually do it",
    "Train linear regression, logistic regression, and tree models with scikit-learn",
    "Evaluate models with accuracy, precision, recall, F1, and ROC-AUC correctly",
    "Diagnose underfitting, overfitting, and data leakage",
    "Build pipelines with ColumnTransformer, Pipeline, and cross-validation",
    "Introduce yourself to neural networks with PyTorch fundamentals",
    "Deliver a complete ML project — problem, data, model, evaluation, write-up",
  ],
  "ai-video-generation": [
    "Generate video in Runway Gen-3, Pika, Kling, and Sora-class tools",
    "Write prompts that produce shot-quality video rather than uncanny noise",
    "Stitch AI-generated clips in DaVinci Resolve or Premiere for a real edit",
    "Lip-sync and dub with HeyGen and ElevenLabs",
    "Upscale and interpolate with Topaz and RIFE for smooth output",
    "Respect IP, likeness, and voice-cloning rules",
    "Produce UGC, explainer, and ad-style videos for real clients",
    "Build a service offer that prices AI-video production sustainably",
  ],
  "building-ai-chatbots": [
    "Design a chatbot with a clear scope, persona, and escape-hatches",
    "Build conversational flows with OpenAI, Claude, or Gemini APIs",
    "Add retrieval (RAG) over a knowledge base with embeddings + vector store",
    "Use function calling to let the bot take actions in real systems",
    "Deploy in web widgets, WhatsApp, Slack, Discord, and Telegram",
    "Handle guardrails, moderation, and prompt-injection defenses",
    "Log conversations and continuously improve prompts from real data",
    "Ship a support, lead-gen, or internal-ops chatbot your users actually return to",
  ],
  "ai-side-hustle-ideas": [
    "Pick an AI-powered side hustle that matches your skills and time budget",
    "Offer services — AI copywriting, AI image ads, AI resumes, AI chatbots",
    "Sell digital products built with AI — templates, prompts, custom GPTs",
    "Use AI to run a content-site or affiliate business faster than humans can",
    "Price AI-augmented work without racing to the bottom",
    "Find first clients on Upwork, Fiverr, and cold outreach in 72 hours",
    "Scale from $1K/month to $5K+/month with repeatable service offers",
    "Avoid the saturated AI hustles and find the ones still open",
  ],

  // ─── Finance & Investing ────────────────────────────────────────────
  "stock-options-trading": [
    "Explain calls, puts, strikes, expirations, and the Greeks in plain language",
    "Read an options chain and pick appropriate strikes and tenors",
    "Run covered calls, cash-secured puts, and wheel strategy for income",
    "Execute verticals, iron condors, and calendars with defined risk",
    "Size positions using account-level risk, not gut feel",
    "Manage trades — roll, close, adjust — based on rules, not emotion",
    "Use thinkorswim or Tastytrade for analysis and order entry",
    "Journal trades and measure real expectancy over hundreds of occurrences",
  ],
  "real-estate-investing": [
    "Analyze a rental deal with the 1% rule, cash-on-cash, and DSCR",
    "Screen markets using Redfin, Zillow, and BiggerPockets data",
    "Build a buy-box and stick to it instead of chasing shiny properties",
    "Finance deals with conventional, DSCR, and creative financing",
    "Underwrite BRRRR, house-hacking, and long-distance rental strategies",
    "Manage properties remotely with a good property manager + KPIs",
    "Build a portfolio that cash-flows and appreciates over 10+ years",
    "Avoid the beginner mistakes that wipe out the first-time investor",
  ],
  "day-trading-beginners": [
    "Explain day-trading mechanics, PDT rules, and broker requirements",
    "Read price action, volume, and level 2 order flow",
    "Identify gap-and-go, VWAP reclaim, and breakout setups",
    "Apply fixed-percentage risk per trade and a hard daily loss limit",
    "Use charting platforms — TradingView, ThinkOrSwim, DAS Trader — efficiently",
    "Journal and review every trade to build a personal edge over time",
    "Manage psychology — tilt, revenge trading, FOMO — with process",
    "Progress from sim to small live size to full size without blowing up",
  ],
  "dividend-investing": [
    "Explain how dividends, payout ratios, and yield-on-cost actually work",
    "Screen for dividend aristocrats, kings, and sustainable-yield stocks",
    "Build a diversified dividend portfolio across sectors and geographies",
    "Use DRIP, tax-advantaged accounts, and qualified-dividend tax treatment",
    "Rebalance and rotate when payout ratios or fundamentals deteriorate",
    "Differentiate high-yield traps from durable dividend growers",
    "Project a 10-, 20-, and 30-year income stream with realistic assumptions",
    "Run a dividend portfolio as a second income stream alongside employment",
  ],
  "personal-finance-mastery": [
    "Set up a zero-based or pay-yourself-first budget that actually holds",
    "Pay down high-interest debt with avalanche or snowball, with a real date",
    "Build and size an emergency fund to your actual expenses and job risk",
    "Open and fund the right accounts — 401k, IRA, HSA, taxable brokerage",
    "Invest in low-cost index funds with a written investment policy statement",
    "Optimize taxes with Roth conversions, backdoor Roth, and HSA stacking",
    "Insure against the risks that actually derail people — health, disability, liability",
    "Run a full yearly money review that sets and tracks real goals",
  ],

  // ─── Productivity & Tools ────────────────────────────────────────────
  "notion-productivity-system": [
    "Design a second-brain in Notion with projects, areas, resources, archives",
    "Build linked databases for tasks, notes, and knowledge",
    "Use relations, rollups, and formulas without over-engineering",
    "Create dashboards that show today's priorities in one view",
    "Capture ideas from web, email, and mobile straight into Notion",
    "Template recurring workflows — weekly review, project kickoff, meeting notes",
    "Collaborate with a team in Notion without permission chaos",
    "Run your life and work from one system that survives six months",
  ],
  "excel-advanced-formulas": [
    "Use INDEX/MATCH, XLOOKUP, and dynamic-array formulas fluently",
    "Build logic with IF, IFS, SWITCH, LET, and LAMBDA",
    "Clean data with Power Query and M language",
    "Analyze data with pivot tables, slicers, and Power Pivot",
    "Build dashboards with charts, conditional formatting, and form controls",
    "Automate repetitive workflows with VBA and Office Scripts",
    "Model a P&L, loan amortization, or scenario analysis from scratch",
    "Pass a finance or analyst Excel interview with confidence",
  ],
  "time-management-mastery": [
    "Audit where your time actually goes with a one-week log",
    "Plan weeks and days with a proven weekly review (GTD / Deep Work)",
    "Block time for deep work and protect it from meetings",
    "Use task systems — Todoist, Things, or Notion — without fiddling",
    "Batch email, Slack, and communication into tight windows",
    "Say no gracefully to low-value asks without burning relationships",
    "Build morning and shutdown routines that compound over quarters",
    "Recover from burnout and reset your system without starting from scratch",
  ],
  "pmp-certification-prep": [
    "Map the PMBOK 7th Edition performance domains to real projects",
    "Apply predictive, agile, and hybrid approaches as the situation demands",
    "Use the exam's situational-question format and process of elimination",
    "Pass mindset questions — servant leadership, stakeholder engagement, tailoring",
    "Practice with 1,500+ questions at exam difficulty until you hit 75%+",
    "Submit the 35-contact-hour and application documentation correctly",
    "Build a 6-week study plan with weekly mock exams",
    "Walk into the PMP exam calm, prepared, and pass on the first attempt",
  ],
  "airtable-business-systems": [
    "Model business data in Airtable bases with linked records done right",
    "Design views — grid, kanban, calendar, Gantt — per stakeholder",
    "Automate with Airtable Automations, scripts, and Interface Designer",
    "Integrate with Make, Zapier, and n8n for cross-tool workflows",
    "Build a CRM, content calendar, or project tracker that a team adopts",
    "Control access with workspace, base, and interface-level permissions",
    "Version, stage, and migrate bases without breaking linked records",
    "Run a small business or ops team entirely on Airtable and love it",
  ],
};
